### ISSUE TITLE
Samples are broken at http://esri.github.io/quickstart-map-js/html/symbols/symbols_polygons.html

### ISSUE THREAD

**Issue by jmalczak** [Esri/quickstart-map-js#116]
init.js:927 dojo.io.script error Error: Token Required.(…)
2015-10-02 16:50:30.742 init.js:205 Error: Token Required.(…) "Error: Token Required.
    at Error (native)
    at Object.l.load (http://js.arcgis.com/3.10compact/init.js:570:220)
    at http://js.arcgis.com/3.10compact/init.js:187:69
    at c (http://js.arcgis.com/3.10compact/init.js:74:221)
    at d (http://js.arcgis.com/3.10compact/init.js:74:10)
    at b.Deferred.a.resolve.callback (http://js.arcgis.com/3.10compact/init.js:75:350)
    at c (http://js.arcgis.com/3.10compact/init.js:74:436)
    at d (http://js.arcgis.com/3.10compact/init.js:74:10)
    at b.Deferred.a.resolve.callback (http://js.arcgis.com/3.10compact/init.js:75:350)
    at http://js.arcgis.com/3.10compact/init.js:925:441"

**Comment by jgravois** [comment]
fixed in 47df36898b9b499e0bfdb08706ae9e8c48726bac
thx for pointing out the problem.

**Comment by dazza222** [comment]
this looks to be broken again.

**Comment by jgravois** [comment]
@dazza222 [the sample](http://esri.github.io/quickstart-map-js/html/symbols/symbols_polygons.html) is running fine on my end.  what exactly are you seeing?

**Comment by dazza222** [comment]
I was not able to get the map to load, so I think is possibly a permissions issue with the map. I got the same message above about a token. When I changed the source to another map it worked fine and the message went away.

**Comment by jgravois** [comment]
both the basemap and feature layer are shared with the world, so i don't think its a permissions problem.

http://server.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Dark_Gray_Base/MapServer/
http://sampleserver6.arcgisonline.com/arcgis/rest/services/Census/MapServer/3

are you seeing errors in the console?  timeouts in the network traffic?  i have seen sampleserver6 acting flaky from time to time, so it could have been a temporary thing.
